export default {
    English:{
       Profile:"Profile",
       Notification:"Notification",
       Settings:"Settings",
       Log_out:"Log out",
       Menu:'Menu',
       Complaint:'Complaint',
       About_Me:"About Me",
       Voter_Id:"Voter Id",
       Blog:"Blog",
       Team_UP:"Join us(BJP)",
       FeedBack:"FeedBack",
       Photos_Gallary:"Photos Gallary",
       View_All:'View All',
       Social_Media:"Social Media",
       Your_Complaint_Details:"YOUR COMPLAINT DETAILS",
       Full_Name:'Full Name',
       Address:"Address",
       Complaint:"Complaint",
       View_More:"View More",
       Your_Suggestion:'Your Suggestion',
       Your_FeedBack:"Your FeedBack",
       Name:'Name',
       Email:'Email',
       Address:'Address',
       City:'City',
       Save:'Save',
       update_password:'Update Password',
       Language:"Language",
       Terms_and_Conditions:"Terms & Conditions",
       Change_Password:"Change Password",
       New_Password:"New Password",
       Confirm_Password:"Confirm Password",
       FeedBack_Saved:"FeedBack Saved",
       Please_Fill_All_Fields:'Please Fill All Fields'
    },
    Marathi:{
        Profile:"प्रोफाइल",
        Notification:"सूचना",
        Settings:"सेटिंग्ज",
        Log_out:"बाहेर पडणे",
        Menu:'मेनू',
        Complaint:'तक्रार नोंदवा',
        About_Me:"माझी माहिती",
        Voter_Id:"वोटर आयडी",
        Blog:"ब्लॉग",
        Team_UP:"आमच्या सोबत या (BJP)",
        FeedBack:"तुमचा प्रतिसाद",
        Photos_Gallary:"फोटो गॅलरी",
        View_All:'सर्व पहा',
        Social_Media:"सोशल मीडिया",
        Your_Complaint_Details:"तुमची तक्रार नोंदवा",
        Full_Name:'तुमचे संपूर्ण नाव',
        Address:"तुमचा पत्ता",
        Complaint:"तक्रार",
        View_More:"आणखी पहा",
        Your_Suggestion:'तुमची सूचना',
        Your_FeedBack:"तुमचा प्रतिसाद",
        Name:'तुमचे नाव',
        Email:'तुमचा इमेल',
        Address:'तुमचा पत्ता',
        City:'तुमचे शहर',
        Save:'साठवून ठेवा',
        update_password:'पासवर्ड अपडेट करा',
        Language:"भाषा बदला",
        Terms_and_Conditions:"नियम व अटी",
        Change_Password:"पासवर्ड बदला",
        New_Password:"नवीन पासवर्ड",
        Confirm_Password:"पासवर्डची पुष्टी करा",
        FeedBack_Saved:"धन्यवाद",
        Please_Fill_All_Fields:'संपूर्ण माहिती भरा'
    },
    Hindi:{
        Profile:"प्रोफाइल",
        Notification:"सूचना",
        Settings:"सेटिंग्ज",
        Log_out:"लॉग आउट",
        Menu:'मेनू',
        Complaint:'शिकायत रजिस्टर करें',
        About_Me:"मेरी जानकारी",
        Voter_Id:"वोटर आयडी",
        Blog:"ब्लॉग",
        Team_UP:"हमारे साथ(BJP)",
        FeedBack:"आपका रिस्पॉन्स",
        Photos_Gallary:"फोटो गॅलरी",
        View_All:'संपूर्ण जानकारी',
        Social_Media:"सोशल मीडिया",
        Your_Complaint_Details:"अपनी शिकायत दर्ज करें",
        Full_Name:'आपका पूरा नाम',
        Address:"आपका पता",
        Complaint:"समस्या",
        View_More:"आणखी पहा",
        Your_Suggestion:'आपको एप्लीकेशन के बारे में क्या लगता है',
        Your_FeedBack:"आपका रिस्पॉन्स",
        Name:'आपका नाम',
        Email:'आपका ई-मेल',
        City:'आपका शहर',
        Save:'जतन कीजिए',
        update_password:'पासवर्ड अपडेट कीजिए',
        Language:"भाषा में बदलाव",
        Terms_and_Conditions:"नियम और स्थि‍ति",
        Change_Password:"पासवर्ड बदलें",
        New_Password:"नया पासवर्ड",
        Confirm_Password:"पासवर्ड की पुष्टि कीजिये",
        FeedBack_Saved:"धन्यवाद",
        Please_Fill_All_Fields:'सारी जानकारी लिखिए'
    }
}

